CarlosNalda.GreenFloydRecords.WebApp/Controllers/ArtistController.cs
using AutoMapper;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Commands.CreateArtist;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Commands.DeleteArtist;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Commands.UpdateArtist;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Queries.GetArtistList;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Queries.GetSingleArtist;
using CarlosNalda.GreenFloydRecords.Domain.Entities;
using CarlosNalda.GreenFloydRecords.WebApp.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace CarlosNalda.GreenFloydRecords.WebApp.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ArtistController(IMapper mapper, IMediator mediator)
        {
            _mapper = mapper;
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            var artists = await _mediator.Send(new GetArtistListQuery());
            return View(_mapper.Map<List<ArtistViewModel>>(artists));
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ArtistViewModel artist)
        {
            if (!ModelState.IsValid)
                return View(artist);

            var request = _mapper.Map<CreateArtistCommand>(artist);
            _ = await _mediator.Send(request);

            TempData["success"] = "Artist created successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            var artist = await _mediator.Send(new GetSingleArtistQuery { Id = parsedId });

            return View(_mapper.Map<ArtistViewModel>(artist));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ArtistViewModel artist)
        {
            if (!ModelState.IsValid)
                return View(artist);

            _ = await _mediator.Send(new GetSingleArtistQuery { Id = artist.Id });

            var request = _mapper.Map<UpdateArtistCommand>(artist);
            await _mediator.Send(request);

            TempData["success"] = "Artist updated successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            var artist = await _mediator.Send(new GetSingleArtistQuery { Id = parsedId });

            return View(_mapper.Map<ArtistViewModel>(artist));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWithPost(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            _ = await _mediator.Send(new GetSingleArtistQuery { Id = parsedId });

            await _mediator.Send(new DeleteArtistCommand { Id = parsedId });


            TempData["success"] = "Artist deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

CarlosNalda.GreenFloydRecords.WebApp/Controllers/GenreController.cs
using AutoMapper;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Commands.CreateGenre;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Commands.DeleteGenre;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Commands.UpdateGenre;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Queries.GetGenreList;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Queries.GetSingleGenre;
using CarlosNalda.GreenFloydRecords.WebApp.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace CarlosNalda.GreenFloydRecords.WebApp.Controllers
{
    public class GenreController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public GenreController(IMapper mapper, IMediator mediator)
        {
            _mapper = mapper;
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            var genres = await _mediator.Send(new GetGenreListQuery());
            return View(_mapper.Map<List<GenreViewModel>>(genres));
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GenreViewModel genre)
        {
            if (char.IsDigit(genre.Name.ToCharArray()[0]))
                ModelState.AddModelError("name", "Name can not start with digit.");

            if (!ModelState.IsValid)
                return View(genre);

            var request = _mapper.Map<CreateGenreCommand>(genre);
            _ = await _mediator.Send(request);

            TempData["success"] = "Genre created successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            var genre = await _mediator.Send(new GetSingleGenreQuery { Id = parsedId });

            return View(_mapper.Map<GenreViewModel>(genre));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GenreViewModel genre)
        {
            if (char.IsDigit(genre.Name.ToCharArray()[0]))
                ModelState.AddModelError("name", "Name can not start with digit.");

            if (!ModelState.IsValid)
                return View(genre);

            var request = _mapper.Map<UpdateGenreCommand>(genre);
            await _mediator.Send(request);

            TempData["success"] = "Genre updated successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            var genre = await _mediator.Send(new GetSingleGenreQuery { Id = parsedId });

            return View(_mapper.Map<GenreViewModel>(genre));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWithPost(string? id)
        {
            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            await _mediator.Send(new DeleteGenreCommand { Id = parsedId });

            TempData["success"] = "Genre deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

CarlosNalda.GreenFloydRecords.WebApp/Controllers/VinylRecordController.cs
using AutoMapper;
using CarlosNalda.GreenFloydRecords.Application.Contracts.Infrastructure;
using CarlosNalda.GreenFloydRecords.Application.Features.Artists.Queries.GetArtistList;
using CarlosNalda.GreenFloydRecords.Application.Features.Genres.Queries.GetGenreList;
using CarlosNalda.GreenFloydRecords.Application.Features.VinylRecords.Commands.CreateVinylRecord;
using CarlosNalda.GreenFloydRecords.Application.Features.VinylRecords.Commands.DeleteVinylRecord;
using CarlosNalda.GreenFloydRecords.Application.Features.VinylRecords.Commands.UpdateVinylRecord;
using CarlosNalda.GreenFloydRecords.Application.Features.VinylRecords.Queries.GetSingleVinylRecord;
using CarlosNalda.GreenFloydRecords.Application.Features.VinylRecords.Queries.GetVinylRecordList;
using CarlosNalda.GreenFloydRecords.WebApp.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarlosNalda.GreenFloydRecords.WebApp.Controllers
{
    public class VinylRecordController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly IImageFileManager _imageFileManager;

        public VinylRecordController(IMapper mapper,
            IMediator mediator,
            IImageFileManager imageFileManager)
        {
            _mapper = mapper;
            _mediator = mediator;
            _imageFileManager = imageFileManager;
        }

        public IActionResult Index() => View();

        public async Task<IActionResult> Upsert(string? id)
        {
            VinylRecordUserInterfaceViewModel VinylRecordVm = await GetVinylRecordVmAsync();

            if (string.IsNullOrEmpty(id))
                return View(VinylRecordVm);

            if (!Guid.TryParse(id, out Guid parsedId))
                return NotFound();

            var vinylRecord = await _mediator.Send(new GetSingleVinylRecordQuery() { Id = parsedId });
            VinylRecordVm.VinylRecord = _mapper.Map<VinylRecordViewModel>(vinylRecord);

            if (VinylRecordVm.VinylRecord == null)
                return NotFound();

            return View(VinylRecordVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(VinylRecordUserInterfaceViewModel viewModel, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                viewModel.GenreList = (await _mediator.Send(new GetGenreListQuery()))
                    .Select(g => MutateToSelectListItem(g.Id, g.Name));
                viewModel.ArtistList = (await _mediator.Send(new GetArtistListQuery()))
                    .Select(a => MutateToSelectListItem(a.Id, a.Name)).ToList();

                return View(viewModel);
            }

            if (viewModel.VinylRecord.Id == default)
            {
                var createVinylRecordCommand = _mapper.Map<CreateVinylRecordCommand>(viewModel.VinylRecord);
                if (file != null)
                {
                    createVinylRecordCommand.ImageStream = file.OpenReadStream();
                }
                _ = await _mediator.Send(createVinylRecordCommand);
            }
            else
            {

                _ = await _mediator.Send(new GetSingleVinylRecordQuery() { Id = viewModel.VinylRecord.Id });

                var updateVinylRecordCommand = _mapper.Map<UpdateVinylRecordCommand>(viewModel.VinylRecord);
                await _mediator.Send(updateVinylRecordCommand);
            }

            TempData["success"] = "Vinyl record created successfully";
            return RedirectToAction("Index");
        }

        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var vinylRecordList = await _mediator.Send(new GetVinylRecordListQuery() { IncludeProperties = "Genre,Artist" });
            return Json(new { data = vinylRecordList });
        }

        //POST
        [HttpDelete]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return Json(new { success = false, message = "Error while deleting" });

            // To check if exist, could be better if implementing a GetFirstOrDefaultVinylRecordQuery or CheckIfExistsVinylRecordQuery
            var vinylRecord = await _mediator.Send(new GetSingleVinylRecordQuery() { Id = id.GetValueOrDefault() });

            if (vinylRecord == null)
                return Json(new { success = false, message = "Error while deleting" });

            // Que pasa si aqui le meto una excepcion
            _imageFileManager.DeleteFile(vinylRecord.ImageUrl);
            await _mediator.Send(new DeleteVinylRecordCommand { Id = id.Value });

            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion

        #region Controller private methods
        private async Task<VinylRecordUserInterfaceViewModel> GetVinylRecordVmAsync()
        {
            return new VinylRecordUserInterfaceViewModel
            {
                VinylRecord = new(),
                GenreList = (await _mediator.Send(new GetGenreListQuery()))
                  .Select(g => MutateToSelectListItem(g.Id, g.Name)),
                ArtistList = (await _mediator.Send(new GetArtistListQuery()))
                  .Select(a => MutateToSelectListItem(a.Id, a.Name))
            };
        }

        private SelectListItem MutateToSelectListItem(Guid id, string text) =>
            new SelectListItem
            {
                Value = id.ToString(),
                Text = text,
            };
        #endregion
    }
}

CarlosNalda.GreenFloydRecords.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Green Floyd Records</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/CarlosNalda.GreenFloydRecords.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-success" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" title="core" alt="" width="40" height="40" />
                    Green Floyd Records
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Genre" asp-action="Index">Genre</a>
                                <a class="dropdown-item" asp-controller="Artist" asp-action="Index">Artist</a>
                                <a class="dropdown-item" asp-controller="VinylRecord" asp-action="Index">Vinyl Record</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Green Floyd Records
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarlosNalda.GreenFloydRecords.WebApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}